version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEO4J_URI=neo4j://localhost:7690
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=yyyyyyyy
      - PYTHON_SERVICE_URL=http://python-service:8000
    depends_on:
      - neo4j
      - python-service

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=neo4j://localhost:7690
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=yyyyyyyy
      - MODEL_PATH=/app/models/node-embeddings.pt
    volumes:
      - ./python-service/models:/app/models
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.15.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs:
